import { Resource, EmergencyScenario } from "@/types";

export const DEMO_RESOURCES: Resource[] = [
  {
    id: "r1",
    name: "Griffith Park Emergency Shelter",
    type: "Shelter",
    address: "4730 Crystal Springs Dr, Los Angeles, CA 90027",
    location: { lat: 34.1341, lng: -118.2945 },
    status: "open",
    services: ["shelter", "water", "food", "wifi"],
    capacity: 200,
    trustScore: 92,
    lastUpdated: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    notes: "Red Cross operated. Cots available. Generator-powered Wi-Fi.",
    distanceMiles: 0.8,
    recommendationScore: 91,
  },
  {
    id: "r2",
    name: "LADWP Charging Hub – Silver Lake",
    type: "Charging Station",
    address: "1818 Glendale Blvd, Los Angeles, CA 90026",
    location: { lat: 34.0856, lng: -118.2669 },
    status: "open",
    services: ["power", "wifi"],
    capacity: 40,
    trustScore: 88,
    lastUpdated: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    notes: "20 USB-A/C ports, 4 outlets. Free. Open 24h during outage.",
    distanceMiles: 1.2,
    recommendationScore: 88,
  },
  {
    id: "r3",
    name: "Echo Park Library – Wi-Fi & Cooling",
    type: "Cooling Center",
    address: "1410 W Temple St, Los Angeles, CA 90026",
    location: { lat: 34.0712, lng: -118.2705 },
    status: "open",
    services: ["wifi", "cooling", "power"],
    capacity: 80,
    trustScore: 85,
    lastUpdated: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    notes: "Library open as cooling center. Free Wi-Fi. Limited outlets.",
    distanceMiles: 1.9,
    recommendationScore: 83,
  },
  {
    id: "r4",
    name: "Downtown LA Water Distribution",
    type: "Water Station",
    address: "201 N Los Angeles St, Los Angeles, CA 90012",
    location: { lat: 34.0534, lng: -118.2468 },
    status: "open",
    services: ["water", "food"],
    capacity: null,
    trustScore: 79,
    lastUpdated: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    notes: "City-run water and MRE distribution. Bring ID if possible.",
    distanceMiles: 3.1,
    recommendationScore: 72,
  },
  {
    id: "r5",
    name: "Koreatown Medical Clinic – Urgent Care",
    type: "Medical",
    address: "3700 W 6th St, Los Angeles, CA 90020",
    location: { lat: 34.0612, lng: -118.3069 },
    status: "limited",
    services: ["medical"],
    capacity: 20,
    trustScore: 74,
    lastUpdated: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    notes: "Walk-ins accepted but wait times are long (2–3 hrs). No power.",
    distanceMiles: 2.5,
    recommendationScore: 60,
  },
  {
    id: "r6",
    name: "McDonald's – Charging & Wi-Fi (Los Feliz)",
    type: "Commercial",
    address: "4421 Hollywood Blvd, Los Angeles, CA 90027",
    location: { lat: 34.0988, lng: -118.2889 },
    status: "open",
    services: ["power", "wifi", "food"],
    capacity: 60,
    trustScore: 65,
    lastUpdated: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    notes: "Generator running. Free Wi-Fi. Outlets at most booths.",
    distanceMiles: 1.5,
    recommendationScore: 66,
  },
  {
    id: "r7",
    name: "Elysian Park Cooling Station",
    type: "Cooling Center",
    address: "929 Academy Rd, Los Angeles, CA 90012",
    location: { lat: 34.0776, lng: -118.2406 },
    status: "limited",
    services: ["cooling", "water"],
    capacity: 50,
    trustScore: 58,
    lastUpdated: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    notes: "Running low on supplies. May close by 8pm.",
    distanceMiles: 2.8,
    recommendationScore: 47,
  },
  {
    id: "r8",
    name: "East Hollywood Community Center",
    type: "Shelter",
    address: "131 N Vermont Ave, Los Angeles, CA 90004",
    location: { lat: 34.0818, lng: -118.2918 },
    status: "closed",
    services: ["shelter", "water"],
    capacity: 100,
    trustScore: 40,
    lastUpdated: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    notes: "Reached capacity. Redirecting to Griffith Park Shelter.",
    distanceMiles: 2.0,
    recommendationScore: 10,
  },
];

export const EMERGENCY_SCENARIOS: EmergencyScenario[] = [
  {
    id: "power_outage",
    label: "Power Outage",
    icon: "⚡",
    description: "No electricity at home or in your neighborhood",
    defaultNeeds: ["power", "wifi"],
  },
  {
    id: "wildfire",
    label: "Wildfire",
    icon: "🔥",
    description: "Wildfire nearby — need evacuation or shelter",
    defaultNeeds: ["shelter", "water", "medical"],
  },
  {
    id: "heat_wave",
    label: "Extreme Heat",
    icon: "☀️",
    description: "Dangerous temperatures, need cooling",
    defaultNeeds: ["cooling", "water"],
  },
  {
    id: "flood",
    label: "Flood",
    icon: "🌊",
    description: "Flooding in the area — need high ground or shelter",
    defaultNeeds: ["shelter", "food", "water"],
  },
];

/** Best pick: highest recommendationScore among open resources */
export function getBestResource(resources: Resource[]): Resource | null {
  const open = resources.filter((r) => r.status === "open");
  if (!open.length) return null;
  return open.reduce((best, r) =>
    (r.recommendationScore ?? 0) > (best.recommendationScore ?? 0) ? r : best
  );
}
